version: "3.3"
services:
  autofeur_nova:
    build: autofeur_nova
    restart: always
    depends_on:
      - deep_phonemizer
      - nats
    environment:
      - NATS=nats
      - REST=http://rest:8090/api
      - PHONEMIZER=http://deep_phonemizer:8000/
  deep_phonemizer:
    build: deep_phonemizer
    restart: always

  nats:
    image: nats
    restart: always
  
  redis:
    image: redis
    restart: always

  cache:
    image: ghcr.io/discordnova/nova/cache
    restart: always
    volumes:
      - ./autofeur_nova/config/default.yml:/config/default.yml
    depends_on:
      - nats
      - redis
  
  gateway:
    image: ghcr.io/discordnova/nova/gateway
    restart: always
    volumes:
      - ./autofeur_nova/config/default.yml:/config/default.yml
    depends_on:
      - nats

  rest:
    image: ghcr.io/discordnova/nova/rest
    restart: always
    volumes:
      - ./autofeur_nova/config/default.yml:/config/default.yml
    depends_on:
      - ratelimiter

  webhook:
    image: ghcr.io/discordnova/nova/webhook
    restart: always
    volumes:
      - ./autofeur_nova/config/default.yml:/config/default.yml
    depends_on:
      - nats

  ratelimiter:
    image: ghcr.io/discordnova/nova/ratelimit
    restart: always
    volumes:
      - ./autofeur_nova/config/default.yml:/config/default.yml
    depends_on:
      - nats
      - redis
