services:
  discordjs_bot:
    build: discordjs
    restart: always
    env_file: .env
    depends_on:
      - autofeur_db
    environment:
      - DB=http://autofeur_db:3000/
  
  autofeur_db:
    build: autofeur_db
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - deep_phonemizer
    environment:
      - PHONEMIZER=http://deep_phonemizer:8000/
    volumes:
      - ./autofeur_db/assets/db.bin:/app/assets/db.bin
  
  deep_phonemizer:
    build: deep_phonemizer
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./deep_phonemizer/assets/model.pt:/app/assets/model.pt
