gateway:
  token: <token>
  intents: 3276799
  shard: 0
  shard_total: 1

rest:
  discord:
    token: <token>
  server:
    port: 8090
    address: 0.0.0.0

webhook:
  discord:
    public_key: <public key>
    client_id: <user id>
  server:
    port: 8091
    address: 0.0.0.0

cache:
  toggles:
    - channels_cache
    - guilds_cache
    - guild_schedules_cache
    - stage_instances_cache
    - integrations_cache
    - members_cache
    - bans_cache
    - reactions_cache
    - messages_cache
    - threads_cache
    - invites_cache
    - roles_cache
    - automoderation_cache
    - voice_states_cache

ratelimiter:
  

# Prometheus monitoring configuration
monitoring:
  enabled: false
  address: 0.0.0.0
  port: 9000

# Nats broker configuration
nats:
  host: nats

redis:
  url: redis://redis
